apiVersion: v1
kind: ConfigMap
metadata:
  name: fiapx-video-service
  namespace: fiapx
data:
  AWS_REGION: "us-east-1"
  SERVER_PORT: "8080"
  DB_URL: "jdbc:postgresql://${DB_HOST}:5432/fiapx_video?sslmode=verify-full&sslrootcert=/etc/fiapx/ca/rds-ca.pem"
  JAVA_TOOL_OPTIONS: "-XX:MaxRAMPercentage=65.0 -Djava.io.tmpdir=/tmp"
  IDENTITY_URL: "http://fiapx-identity-service:8080"
  JWT_PUBLIC_KEY: "file:/etc/fiapx/credentials/public.pem"
  MEDIA_BUCKET_NAME: "${MEDIA_BUCKET_NAME}"
  PROCESSING_QUEUE_URL: "${PROCESSING_QUEUE_URL}"
  VIDEOS_EVENTS_QUEUE_URL: "${VIDEOS_EVENTS_QUEUE_URL}"
  UPLOAD_ENABLED: "true"
  UPLOAD_PUBLISHER_ENABLED: "true"
  PROCESSING_RECONCILE_ENABLED: "true"
  PROCESSING_RESULTS_ENABLED: "true"
  DOWNLOAD_ENABLED: "true"
  RESULT_CLEANUP_ENABLED: "true"
  UPLOAD_TEMP_DIRECTORY: "/app/.local/uploads"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fiapx-video-service-ca
  namespace: fiapx
binaryData:
  rds-ca.pem: "${RDS_CA_B64}"
